// Mocks generated by Mockito 5.4.6 from annotations
// in chatapp/test/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chatapp/services/api_service.dart' as _i2;
import 'package:chatapp/services/socket_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setToken(String? token) => super.noSuchMethod(
    Invocation.method(#setToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearToken() => super.noSuchMethod(
    Invocation.method(#clearToken, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<Map<String, dynamic>> get(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> post(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#post, [endpoint, body]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> put(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#put, [endpoint, body]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> delete(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [SocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketService extends _i1.Mock implements _i4.SocketService {
  MockSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Map<String, dynamic>> get onNewMessage =>
      (super.noSuchMethod(
            Invocation.getter(#onNewMessage),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> get onMessageStatus =>
      (super.noSuchMethod(
            Invocation.getter(#onMessageStatus),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> get onTyping =>
      (super.noSuchMethod(
            Invocation.getter(#onTyping),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> get onUserOnline =>
      (super.noSuchMethod(
            Invocation.getter(#onUserOnline),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> get onMessagesRead =>
      (super.noSuchMethod(
            Invocation.getter(#onMessagesRead),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> get onConversationUpdate =>
      (super.noSuchMethod(
            Invocation.getter(#onConversationUpdate),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  void connect(String? token) => super.noSuchMethod(
    Invocation.method(#connect, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void sendMessage({
    required String? receiverId,
    required String? content,
    String? messageType = 'text',
    String? imageUrl = '',
    String? replyToId,
  }) => super.noSuchMethod(
    Invocation.method(#sendMessage, [], {
      #receiverId: receiverId,
      #content: content,
      #messageType: messageType,
      #imageUrl: imageUrl,
      #replyToId: replyToId,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void sendTypingStart(String? receiverId) => super.noSuchMethod(
    Invocation.method(#sendTypingStart, [receiverId]),
    returnValueForMissingStub: null,
  );

  @override
  void sendTypingStop(String? receiverId) => super.noSuchMethod(
    Invocation.method(#sendTypingStop, [receiverId]),
    returnValueForMissingStub: null,
  );

  @override
  void markAsRead(String? senderId) => super.noSuchMethod(
    Invocation.method(#markAsRead, [senderId]),
    returnValueForMissingStub: null,
  );

  @override
  void sendGroupMessage({
    required String? groupId,
    required String? content,
    String? messageType = 'text',
    String? imageUrl = '',
  }) => super.noSuchMethod(
    Invocation.method(#sendGroupMessage, [], {
      #groupId: groupId,
      #content: content,
      #messageType: messageType,
      #imageUrl: imageUrl,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
